/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hs.demo.model.protocol;

@SuppressWarnings("all")
/** Protocol Greetings */
@org.apache.avro.specific.AvroGenerated
public interface AvroHelloWorld {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AvroHelloWorld\",\"namespace\":\"com.hs.demo.model.protocol\",\"doc\":\"Protocol Greetings\",\"types\":[{\"type\":\"record\",\"name\":\"Greeting\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"},{\"name\":\"password\",\"type\":\"string\"}]}],\"messages\":{\"hello\":{\"doc\":\"Say hello.\",\"request\":[{\"name\":\"greeting\",\"type\":\"Greeting\"}],\"response\":\"Greeting\"}}}");
  /**
   * Say hello.
   */
  com.hs.demo.model.protocol.Greeting hello(com.hs.demo.model.protocol.Greeting greeting) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** Protocol Greetings */
  public interface Callback extends AvroHelloWorld {
    public static final org.apache.avro.Protocol PROTOCOL = com.hs.demo.model.protocol.AvroHelloWorld.PROTOCOL;
    /**
     * Say hello.
     * @throws java.io.IOException The async call could not be completed.
     */
    void hello(com.hs.demo.model.protocol.Greeting greeting, org.apache.avro.ipc.Callback<com.hs.demo.model.protocol.Greeting> callback) throws java.io.IOException;
  }
}