/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hs.easyrpc.demo.model.protocol;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Greeting extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1961483725036949998L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Greeting\",\"namespace\":\"com.hs.easyrpc.demo.model.protocol\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"},{\"name\":\"password\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Greeting> ENCODER =
      new BinaryMessageEncoder<Greeting>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Greeting> DECODER =
      new BinaryMessageDecoder<Greeting>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Greeting> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Greeting> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Greeting>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Greeting to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Greeting from a ByteBuffer. */
  public static Greeting fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence message;
  @Deprecated public java.lang.CharSequence password;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Greeting() {}

  /**
   * All-args constructor.
   * @param message The new value for message
   * @param password The new value for password
   */
  public Greeting(java.lang.CharSequence message, java.lang.CharSequence password) {
    this.message = message;
    this.password = password;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message;
    case 1: return password;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message = (java.lang.CharSequence)value$; break;
    case 1: password = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }

  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'password' field.
   * @return The value of the 'password' field.
   */
  public java.lang.CharSequence getPassword() {
    return password;
  }

  /**
   * Sets the value of the 'password' field.
   * @param value the value to set.
   */
  public void setPassword(java.lang.CharSequence value) {
    this.password = value;
  }

  /**
   * Creates a new Greeting RecordBuilder.
   * @return A new Greeting RecordBuilder
   */
  public static com.hs.easyrpc.demo.model.protocol.Greeting.Builder newBuilder() {
    return new com.hs.easyrpc.demo.model.protocol.Greeting.Builder();
  }

  /**
   * Creates a new Greeting RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Greeting RecordBuilder
   */
  public static com.hs.easyrpc.demo.model.protocol.Greeting.Builder newBuilder(com.hs.easyrpc.demo.model.protocol.Greeting.Builder other) {
    return new com.hs.easyrpc.demo.model.protocol.Greeting.Builder(other);
  }

  /**
   * Creates a new Greeting RecordBuilder by copying an existing Greeting instance.
   * @param other The existing instance to copy.
   * @return A new Greeting RecordBuilder
   */
  public static com.hs.easyrpc.demo.model.protocol.Greeting.Builder newBuilder(com.hs.easyrpc.demo.model.protocol.Greeting other) {
    return new com.hs.easyrpc.demo.model.protocol.Greeting.Builder(other);
  }

  /**
   * RecordBuilder for Greeting instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Greeting>
    implements org.apache.avro.data.RecordBuilder<Greeting> {

    private java.lang.CharSequence message;
    private java.lang.CharSequence password;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hs.easyrpc.demo.model.protocol.Greeting.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.password)) {
        this.password = data().deepCopy(fields()[1].schema(), other.password);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Greeting instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hs.easyrpc.demo.model.protocol.Greeting other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.password)) {
        this.password = data().deepCopy(fields()[1].schema(), other.password);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }

    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.hs.easyrpc.demo.model.protocol.Greeting.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.message = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public com.hs.easyrpc.demo.model.protocol.Greeting.Builder clearMessage() {
      message = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'password' field.
      * @return The value.
      */
    public java.lang.CharSequence getPassword() {
      return password;
    }

    /**
      * Sets the value of the 'password' field.
      * @param value The value of 'password'.
      * @return This builder.
      */
    public com.hs.easyrpc.demo.model.protocol.Greeting.Builder setPassword(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.password = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'password' field has been set.
      * @return True if the 'password' field has been set, false otherwise.
      */
    public boolean hasPassword() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'password' field.
      * @return This builder.
      */
    public com.hs.easyrpc.demo.model.protocol.Greeting.Builder clearPassword() {
      password = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Greeting build() {
      try {
        Greeting record = new Greeting();
        record.message = fieldSetFlags()[0] ? this.message : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.password = fieldSetFlags()[1] ? this.password : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Greeting>
    WRITER$ = (org.apache.avro.io.DatumWriter<Greeting>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Greeting>
    READER$ = (org.apache.avro.io.DatumReader<Greeting>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
